/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { RetailerManagement } from "./RetailerManagement";
import { RetailerManagementCountArgs } from "./RetailerManagementCountArgs";
import { RetailerManagementFindManyArgs } from "./RetailerManagementFindManyArgs";
import { RetailerManagementFindUniqueArgs } from "./RetailerManagementFindUniqueArgs";
import { DeleteRetailerManagementArgs } from "./DeleteRetailerManagementArgs";
import { RetailerManagementService } from "../retailerManagement.service";
@graphql.Resolver(() => RetailerManagement)
export class RetailerManagementResolverBase {
  constructor(protected readonly service: RetailerManagementService) {}

  async _retailerManagementsMeta(
    @graphql.Args() args: RetailerManagementCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [RetailerManagement])
  async retailerManagements(
    @graphql.Args() args: RetailerManagementFindManyArgs
  ): Promise<RetailerManagement[]> {
    return this.service.retailerManagements(args);
  }

  @graphql.Query(() => RetailerManagement, { nullable: true })
  async retailerManagement(
    @graphql.Args() args: RetailerManagementFindUniqueArgs
  ): Promise<RetailerManagement | null> {
    const result = await this.service.retailerManagement(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => RetailerManagement)
  async deleteRetailerManagement(
    @graphql.Args() args: DeleteRetailerManagementArgs
  ): Promise<RetailerManagement | null> {
    try {
      return await this.service.deleteRetailerManagement(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
